services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - PROVIDER_URL=https://provider.code-challenge.feverup.com/api/events
    depends_on:
      - redis
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./src
    #       target: /src
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: package.json

  redis:
    image: 'redis:6-alpine'
    ports:
      - '6379:6379'
